"""
BoilerGame: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

import argparse
import runpy
import sys
from pathlib import Path

from kinner_runtime import (Application, Buffer, Component, DisabledActionError, InvariantViolation, SendSlot, Transition)

from Boiler import Boiler


class BoilerGame(Application):
    DisabledActionError = DisabledActionError
    InvariantViolation = InvariantViolation

    @property
    def p_boilerState(self) -> str:
        return f"P_{self._components['P'].state}"

    @property
    def p_boilerMatch(self) -> bool:
        return self._components['P'].match

    @property
    def p_boilerFurnace(self) -> bool:
        return self._components['P'].furnace

    @property
    def p_boilerCw(self) -> bool:
        return self._components['P'].cw

    @property
    def p_boilerClunk(self) -> bool:
        return self._components['P'].clunk

    @property
    def p_boilerWindow(self) -> int:
        return self._components['P'].window

    @property
    def p_boilerAtTree(self) -> bool:
        return self._components['P'].atTree

    _tla_state_vars: tuple[str, ...] = ('p_boilerState', 'p_boilerMatch', 'p_boilerFurnace', 'p_boilerCw', 'p_boilerClunk', 'p_boilerWindow', 'p_boilerAtTree',)
    _tla_channel_vars: tuple[str, ...] = ()

    def __init__(self, seed: int = 0) -> None:
        super().__init__(seed=seed)
        self._register('P', Boiler())

        self._bind()

        self._register_invariant(
            'P_NeverSolved',
            lambda app: (app._components['P'].state != 'Open'),
        )

        self._call_hook('on_init')
        self._evaluate_invariants()

    def _bind(self) -> None:
        pass

    @classmethod
    def main(cls, argv: list[str] | None = None) -> int:
        parser = argparse.ArgumentParser(
            description=f'{cls.__name__}: run spec-driven application',
        )
        parser.add_argument('--run', type=Path)
        parser.add_argument('--seed', type=int, default=0)
        parser.add_argument('--seeds', type=int, default=None)
        args = parser.parse_args(argv)

        if args.run is not None:
            app = cls(seed=args.seed)
            runpy.run_path(str(args.run), init_globals={'app': app})
            return 0

        if args.seeds is not None:
            for seed in range(args.seeds):
                app = cls(seed=seed)
                while app.step() is not None:
                    pass
            return 0

        app = cls(seed=args.seed)
        while app.step() is not None:
            pass
        return 0

if __name__ == '__main__':
    sys.exit(BoilerGame.main())
