"""
Boiler: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class Boiler(Component):
    initial_state = 'Cabin'
    state_constants = ('Cabin', 'TreeRising', 'Open',)
    _in_ports = ()
    _out_ports = ()
    _observe_ports = ()
    _option_defaults = {}
    _option_constants = {}
    _typed_var_defaults = {'match': False, 'furnace': False, 'cw': False, 'clunk': False, 'window': 0, 'atTree': False}
    _typed_var_bounds = {'window': (0, 3)}

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='Boiler_OpenTheWallSafeAndTakeTheMatch',
            from_state='Cabin',
            to_state='Cabin',
            kind='local',
            guard_fn=lambda self: (not self.match),
            assigns=(('match', lambda self: True),),
        ),
        Transition(
            name='Boiler_LightTheMatchAndPutItInTheFurnace',
            from_state='Cabin',
            to_state='Cabin',
            kind='local',
            guard_fn=lambda self: (self.match and (not self.furnace)),
            assigns=(('furnace', lambda self: True),),
        ),
        Transition(
            name='Boiler_TurnTheRightWheelClockwiseUntilItBlocks',
            from_state='Cabin',
            to_state='Cabin',
            kind='local',
            guard_fn=lambda self: (self.furnace and (not self.cw)),
            assigns=(('cw', lambda self: True),),
        ),
        Transition(
            name='Boiler_WaitForTheClunkingToCease',
            from_state='Cabin',
            to_state='Cabin',
            kind='local',
            guard_fn=lambda self: (self.cw and (not self.clunk)),
            assigns=(('clunk', lambda self: True),),
        ),
        Transition(
            name='Boiler_TurnTheWheelCounterclockwiseUntilTheFireGoesOutTheTreeRises',
            from_state='Cabin',
            to_state='TreeRising',
            kind='local',
            guard_fn=lambda self: self.clunk,
            assigns=(('window', lambda self: 3), ('atTree', lambda self: False),),
        ),
        Transition(
            name='Boiler_RushOutOfTheCabinToTheGreatTree',
            from_state='TreeRising',
            to_state='TreeRising',
            kind='local',
            guard_fn=lambda self: ((self.window > 0) and (not self.atTree)),
            assigns=(('atTree', lambda self: True), ('window', lambda self: (self.window - 1)),),
        ),
        Transition(
            name='Boiler_ClimbTheRisingTreeToTheLinkingBook',
            from_state='TreeRising',
            to_state='Open',
            kind='local',
            guard_fn=lambda self: (self.atTree and (self.window > 0)),
        ),
        Transition(
            name='Boiler_TooSlowTheTreeSinksReFire',
            from_state='TreeRising',
            to_state='Cabin',
            kind='local',
            guard_fn=lambda self: (self.window == 0),
            assigns=(('furnace', lambda self: False), ('cw', lambda self: False), ('clunk', lambda self: False), ('atTree', lambda self: False),),
        ),
        Transition(
            name='Boiler_Solved',
            from_state='Open',
            to_state='Open',
            kind='local',
        ),
        ]
