"""
MystClockTower: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class MystClockTower(Component):
    initial_state = 'SettingClock'
    state_constants = ('SettingClock', 'GearTower', 'Open',)
    _in_ports = ()
    _out_ports = ()
    _observe_ports = ()
    _option_defaults = {'targetHour': 2, 'targetMinIdx': 8, 'gearTop': 2, 'gearMid': 2, 'gearBot': 1}
    _option_constants = {'TargetHour': 'targetHour', 'TargetMinIdx': 'targetMinIdx', 'GearTop': 'gearTop', 'GearMid': 'gearMid', 'GearBot': 'gearBot'}
    _typed_var_defaults = {'hour': 0, 'minIdx': 0, 'top': 0, 'mid': 0, 'bot': 0}
    _typed_var_bounds = {'hour': (0, 11), 'minIdx': (0, 11), 'top': (0, 2), 'mid': (0, 2), 'bot': (0, 2)}

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='ClockTower_TurnTheLargeWheelMinuteHand5',
            from_state='SettingClock',
            to_state='SettingClock',
            kind='local',
            assigns=(('minIdx', lambda self: (0 if (self.minIdx == 11) else (self.minIdx + 1))),),
        ),
        Transition(
            name='ClockTower_TurnTheSmallWheelHourHand1',
            from_state='SettingClock',
            to_state='SettingClock',
            kind='local',
            assigns=(('hour', lambda self: (0 if (self.hour == 11) else (self.hour + 1))),),
        ),
        Transition(
            name='ClockTower_PressTheRedButtonRaiseTheGearBridge',
            from_state='SettingClock',
            to_state='GearTower',
            kind='local',
            guard_fn=lambda self: ((self.hour == self._options['targetHour']) and (self.minIdx == self._options['targetMinIdx'])),
        ),
        Transition(
            name='ClockTower_LeftLeverTapTwoBottomWheels1',
            from_state='GearTower',
            to_state='GearTower',
            kind='local',
            assigns=(('mid', lambda self: (0 if (self.mid == 2) else (self.mid + 1))), ('bot', lambda self: (0 if (self.bot == 2) else (self.bot + 1))),),
        ),
        Transition(
            name='ClockTower_RightLeverTapTwoTopWheels1',
            from_state='GearTower',
            to_state='GearTower',
            kind='local',
            assigns=(('top', lambda self: (0 if (self.top == 2) else (self.top + 1))), ('mid', lambda self: (0 if (self.mid == 2) else (self.mid + 1))),),
        ),
        Transition(
            name='ClockTower_HoldALeverMiddleWheel1',
            from_state='GearTower',
            to_state='GearTower',
            kind='local',
            assigns=(('mid', lambda self: (0 if (self.mid == 2) else (self.mid + 1))),),
        ),
        Transition(
            name='ClockTower_ThirdLeverResetTheGears',
            from_state='GearTower',
            to_state='GearTower',
            kind='local',
            assigns=(('top', lambda self: 0), ('mid', lambda self: 0), ('bot', lambda self: 0),),
        ),
        Transition(
            name='ClockTower_TheTowerOpens',
            from_state='GearTower',
            to_state='Open',
            kind='local',
            guard_fn=lambda self: (((self.top == self._options['gearTop']) and (self.mid == self._options['gearMid'])) and (self.bot == self._options['gearBot'])),
        ),
        Transition(
            name='ClockTower_Solved',
            from_state='Open',
            to_state='Open',
            kind='local',
        ),
        ]
