"""
Channelwood: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class Channelwood(Component):
    initial_state = 'Ground'
    state_constants = ('Ground', 'Upper', 'RodeElevator',)
    _in_ports = ()
    _out_ports = ('GATE',)
    _observe_ports = ()
    _option_defaults = {}
    _option_constants = {}
    _typed_var_defaults = {'water': False, 'windmill': False, 'vStair': False, 'vA': False, 'vB': False, 'vC': False, 'feed': 0, 'upperDone': False, 'crossed': False, 'pipeExt': False}
    _typed_var_bounds = {'feed': (0, 3)}
    _message_set = frozenset({'Push'})

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='Channelwood_TurnTheFaucetOnTheFloorWaterFlowsFromTheWindmill',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: (not self.water),
            assigns=(('water', lambda self: True),),
        ),
        Transition(
            name='Channelwood_TheWindmillTurnsThePipesHavePower',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: (self.water and (not self.windmill)),
            assigns=(('windmill', lambda self: True),),
        ),
        Transition(
            name='Channelwood_SetTheFirstValveToCoverTheLineToTheSpiralStaircase',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: (self.windmill and (not self.vStair)),
            assigns=(('vStair', lambda self: True),),
        ),
        Transition(
            name='Channelwood_SetTheSecondValveSoTheWaterFlowsRight',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: (self.vStair and (not self.vA)),
            assigns=(('vA', lambda self: True),),
        ),
        Transition(
            name='Channelwood_SetTheThirdValveSoTheWaterFlowsRight',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: (self.vA and (not self.vB)),
            assigns=(('vB', lambda self: True),),
        ),
        Transition(
            name='Channelwood_SetTheFourthValveSoTheWaterFlowsLeft',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: (self.vB and (not self.vC)),
            assigns=(('vC', lambda self: True),),
        ),
        Transition(
            name='Channelwood_RouteTheWaterToTheFirstElevator',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: (self.vC and (self.feed != 1)),
            assigns=(('feed', lambda self: 1),),
        ),
        Transition(
            name='Channelwood_RideTheFirstElevatorUpToTheUpperVillage',
            from_state='Ground',
            to_state='Upper',
            kind='local',
            guard_fn=lambda self: (self.feed == 1),
        ),
        Transition(
            name='Channelwood_PullTheHutLeverAndDescendThePoweredStairwayToTheUpperVillage',
            from_state='Upper',
            to_state='Upper',
            kind='local',
            guard_fn=lambda self: (not self.upperDone),
            assigns=(('upperDone', lambda self: True),),
        ),
        Transition(
            name='Channelwood_RideTheFirstElevatorBackDownToTheGround',
            from_state='Upper',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: (self.feed == 1),
        ),
        Transition(
            name='Channelwood_ReRouteTheWaterToTheBridgeMachine',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: ((self.vC and self.upperDone) and (self.feed != 2)),
            assigns=(('feed', lambda self: 2),),
        ),
        Transition(
            name='Channelwood_PullTheBridgeLeverAndCrossTheRaisedBridge',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: ((self.feed == 2) and (not self.crossed)),
            assigns=(('crossed', lambda self: True),),
        ),
        Transition(
            name='Channelwood_TurnTheCrankToExtendTheFinalPipeToTheFarSide',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: (self.crossed and (not self.pipeExt)),
            assigns=(('pipeExt', lambda self: True),),
        ),
        Transition(
            name='Channelwood_ReRouteTheWaterToTheFinalElevator',
            from_state='Ground',
            to_state='Ground',
            kind='local',
            guard_fn=lambda self: (((self.vC and self.crossed) and self.pipeExt) and (self.feed != 3)),
            assigns=(('feed', lambda self: 3),),
        ),
        Transition(
            name='Channelwood_RideTheFinalElevatorUpToTheMystLinkingBook',
            from_state='Ground',
            to_state='RodeElevator',
            kind='send',
            sends=(SendSlot(port='GATE', tag='Push'),),
            guard_fn=lambda self: (((self.feed == 3) and self.pipeExt) and self.crossed),
        ),
        Transition(
            name='Channelwood_Done',
            from_state='RodeElevator',
            to_state='RodeElevator',
            kind='local',
        ),
        ]
