"""
ChannelwoodGame: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

import argparse
import runpy
import sys
from pathlib import Path

from kinner_runtime import (Application, Buffer, Component, DisabledActionError, InvariantViolation, SendSlot, Transition)

from Channelwood import Channelwood


class ChannelwoodGame(Application):
    DisabledActionError = DisabledActionError
    InvariantViolation = InvariantViolation

    @property
    def p_channelwoodState(self) -> str:
        return f"P_{self._components['P'].state}"

    @property
    def p_channelwoodWater(self) -> bool:
        return self._components['P'].water

    @property
    def p_channelwoodWindmill(self) -> bool:
        return self._components['P'].windmill

    @property
    def p_channelwoodVStair(self) -> bool:
        return self._components['P'].vStair

    @property
    def p_channelwoodVA(self) -> bool:
        return self._components['P'].vA

    @property
    def p_channelwoodVB(self) -> bool:
        return self._components['P'].vB

    @property
    def p_channelwoodVC(self) -> bool:
        return self._components['P'].vC

    @property
    def p_channelwoodFeed(self) -> int:
        return self._components['P'].feed

    @property
    def p_channelwoodUpperDone(self) -> bool:
        return self._components['P'].upperDone

    @property
    def p_channelwoodCrossed(self) -> bool:
        return self._components['P'].crossed

    @property
    def p_channelwoodPipeExt(self) -> bool:
        return self._components['P'].pipeExt

    _tla_state_vars: tuple[str, ...] = ('p_channelwoodState', 'p_channelwoodWater', 'p_channelwoodWindmill', 'p_channelwoodVStair', 'p_channelwoodVA', 'p_channelwoodVB', 'p_channelwoodVC', 'p_channelwoodFeed', 'p_channelwoodUpperDone', 'p_channelwoodCrossed', 'p_channelwoodPipeExt',)
    _tla_channel_vars: tuple[str, ...] = ()

    def __init__(self, seed: int = 0) -> None:
        super().__init__(seed=seed)
        self._register('P', Channelwood())

        self._bind()

        self._register_invariant(
            'P_NeverSolved',
            lambda app: (app._components['P'].state != 'RodeElevator'),
        )
        self._register_invariant(
            'P_RodeMeansSolved',
            lambda app: (not ((app._components['P'].state == 'RodeElevator') and (not ((((((app._components['P'].vStair and app._components['P'].vA) and app._components['P'].vB) and app._components['P'].vC) and app._components['P'].upperDone) and app._components['P'].crossed) and app._components['P'].pipeExt)))),
        )

        self._call_hook('on_init')
        self._evaluate_invariants()

    def _bind(self) -> None:
        pass

    @classmethod
    def main(cls, argv: list[str] | None = None) -> int:
        parser = argparse.ArgumentParser(
            description=f'{cls.__name__}: run spec-driven application',
        )
        parser.add_argument('--run', type=Path)
        parser.add_argument('--seed', type=int, default=0)
        parser.add_argument('--seeds', type=int, default=None)
        args = parser.parse_args(argv)

        if args.run is not None:
            app = cls(seed=args.seed)
            runpy.run_path(str(args.run), init_globals={'app': app})
            return 0

        if args.seeds is not None:
            for seed in range(args.seeds):
                app = cls(seed=seed)
                while app.step() is not None:
                    pass
            return 0

        app = cls(seed=args.seed)
        while app.step() is not None:
            pass
        return 0

if __name__ == '__main__':
    sys.exit(ChannelwoodGame.main())
