"""
Stoneship: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class Stoneship(Component):
    initial_state = 'Arrived'
    state_constants = ('Arrived', 'Powered', 'Recovered', 'Blackout',)
    _in_ports = ()
    _out_ports = ('GATE',)
    _observe_ports = ()
    _option_defaults = {}
    _option_constants = {}
    _typed_var_defaults = {'degree': False, 'drainLight': False, 'airTrap': False, 'refloat': False, 'key': False, 'padlock': False, 'trap': False, 'charge': 0, 'drainRock': False, 'tunnels': 0, 'compass': False, 'deck': False}
    _typed_var_bounds = {'charge': (0, 6), 'tunnels': (0, 2)}
    _message_set = frozenset({'Push'})

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='Stoneship_ReadTheLighthouseBearingOffTheTelescope135Degrees',
            from_state='Arrived',
            to_state='Arrived',
            kind='local',
            guard_fn=lambda self: (not self.degree),
            assigns=(('degree', lambda self: True),),
        ),
        Transition(
            name='Stoneship_PressTheRightUmbrellaButtonDrainTheLighthouseStairs',
            from_state='Arrived',
            to_state='Arrived',
            kind='local',
            guard_fn=lambda self: (not self.drainLight),
            assigns=(('drainLight', lambda self: True),),
        ),
        Transition(
            name='Stoneship_DescendTheLighthouseAndTurnTheChestValveToTrapItsAir',
            from_state='Arrived',
            to_state='Arrived',
            kind='local',
            guard_fn=lambda self: (self.drainLight and (not self.airTrap)),
            assigns=(('airTrap', lambda self: True),),
        ),
        Transition(
            name='Stoneship_PressTheRightUmbrellaButtonAgainToRefillTheChestFloatsUp',
            from_state='Arrived',
            to_state='Arrived',
            kind='local',
            guard_fn=lambda self: (self.airTrap and (not self.refloat)),
            assigns=(('refloat', lambda self: True),),
        ),
        Transition(
            name='Stoneship_OpenTheFloatedChestAndTakeTheKey',
            from_state='Arrived',
            to_state='Arrived',
            kind='local',
            guard_fn=lambda self: (self.refloat and (not self.key)),
            assigns=(('key', lambda self: True),),
        ),
        Transition(
            name='Stoneship_UnlockThePadlockWithTheKey',
            from_state='Arrived',
            to_state='Arrived',
            kind='local',
            guard_fn=lambda self: (self.key and (not self.padlock)),
            assigns=(('padlock', lambda self: True),),
        ),
        Transition(
            name='Stoneship_OpenTheTrapdoorAndClimbToTheGenerator',
            from_state='Arrived',
            to_state='Arrived',
            kind='local',
            guard_fn=lambda self: (self.padlock and (not self.trap)),
            assigns=(('trap', lambda self: True),),
        ),
        Transition(
            name='Stoneship_CrankTheGeneratorOneFullRotation',
            from_state='Arrived',
            to_state='Arrived',
            kind='local',
            guard_fn=lambda self: (self.trap and (self.charge < 6)),
            assigns=(('charge', lambda self: (self.charge + 1)),),
        ),
        Transition(
            name='Stoneship_TheBatteriesAreFullTheLightsHavePower',
            from_state='Arrived',
            to_state='Powered',
            kind='local',
            guard_fn=lambda self: (self.charge == 6),
        ),
        Transition(
            name='Stoneship_PressTheMiddleUmbrellaButtonDrainTheRockAndEnterTheTunnels',
            from_state='Powered',
            to_state='Powered',
            kind='local',
            guard_fn=lambda self: (not self.drainRock),
            assigns=(('drainRock', lambda self: True),),
        ),
        Transition(
            name='Stoneship_GoDownATunnelByTheBatterySLightTowardTheCompassBoard',
            from_state='Powered',
            to_state='Powered',
            kind='local',
            guard_fn=lambda self: ((self.drainRock and (self.charge >= 2)) and (self.tunnels < 2)),
            assigns=(('charge', lambda self: (self.charge - 2)), ('tunnels', lambda self: (self.tunnels + 1)),),
        ),
        Transition(
            name='Stoneship_GropeInTheDarkWasteTheCharge',
            from_state='Powered',
            to_state='Powered',
            kind='local',
            guard_fn=lambda self: (self.charge > 0),
            assigns=(('charge', lambda self: (self.charge - 1)),),
        ),
        Transition(
            name='Stoneship_TheBatteriesDieInTheDark',
            from_state='Powered',
            to_state='Blackout',
            kind='local',
            guard_fn=lambda self: ((self.charge == 0) and (not self.compass)),
        ),
        Transition(
            name='Stoneship_WindTheGeneratorBackUpAfterTheBlackout',
            from_state='Blackout',
            to_state='Powered',
            kind='local',
            assigns=(('charge', lambda self: 6),),
        ),
        Transition(
            name='Stoneship_PressTheCompassRoseSoutheastButton135Degrees',
            from_state='Powered',
            to_state='Powered',
            kind='local',
            guard_fn=lambda self: (((self.degree and self.drainRock) and (self.tunnels == 2)) and (not self.compass)),
            assigns=(('compass', lambda self: True),),
        ),
        Transition(
            name='Stoneship_PressAWrongCompassRoseButtonTheLightsGoOutAndTheBatteryDrains',
            from_state='Powered',
            to_state='Blackout',
            kind='local',
            guard_fn=lambda self: ((self.drainRock and (self.tunnels == 2)) and (not self.compass)),
            assigns=(('charge', lambda self: 0),),
        ),
        Transition(
            name='Stoneship_PressTheLeftUmbrellaButtonDrainTheShipDeckAndClickTheTableTheLinkingBookRises',
            from_state='Powered',
            to_state='Recovered',
            kind='send',
            sends=(SendSlot(port='GATE', tag='Push'),),
            guard_fn=lambda self: (self.compass and (not self.deck)),
            assigns=(('deck', lambda self: True),),
        ),
        Transition(
            name='Stoneship_Done',
            from_state='Recovered',
            to_state='Recovered',
            kind='local',
        ),
        ]
