"""
StoneshipGame: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

import argparse
import runpy
import sys
from pathlib import Path

from kinner_runtime import (Application, Buffer, Component, DisabledActionError, InvariantViolation, SendSlot, Transition)

from Stoneship import Stoneship


class StoneshipGame(Application):
    DisabledActionError = DisabledActionError
    InvariantViolation = InvariantViolation

    @property
    def p_stoneshipState(self) -> str:
        return f"P_{self._components['P'].state}"

    @property
    def p_stoneshipDegree(self) -> bool:
        return self._components['P'].degree

    @property
    def p_stoneshipDrainLight(self) -> bool:
        return self._components['P'].drainLight

    @property
    def p_stoneshipAirTrap(self) -> bool:
        return self._components['P'].airTrap

    @property
    def p_stoneshipRefloat(self) -> bool:
        return self._components['P'].refloat

    @property
    def p_stoneshipKey(self) -> bool:
        return self._components['P'].key

    @property
    def p_stoneshipPadlock(self) -> bool:
        return self._components['P'].padlock

    @property
    def p_stoneshipTrap(self) -> bool:
        return self._components['P'].trap

    @property
    def p_stoneshipCharge(self) -> int:
        return self._components['P'].charge

    @property
    def p_stoneshipDrainRock(self) -> bool:
        return self._components['P'].drainRock

    @property
    def p_stoneshipTunnels(self) -> int:
        return self._components['P'].tunnels

    @property
    def p_stoneshipCompass(self) -> bool:
        return self._components['P'].compass

    @property
    def p_stoneshipDeck(self) -> bool:
        return self._components['P'].deck

    _tla_state_vars: tuple[str, ...] = ('p_stoneshipState', 'p_stoneshipDegree', 'p_stoneshipDrainLight', 'p_stoneshipAirTrap', 'p_stoneshipRefloat', 'p_stoneshipKey', 'p_stoneshipPadlock', 'p_stoneshipTrap', 'p_stoneshipCharge', 'p_stoneshipDrainRock', 'p_stoneshipTunnels', 'p_stoneshipCompass', 'p_stoneshipDeck',)
    _tla_channel_vars: tuple[str, ...] = ()

    def __init__(self, seed: int = 0) -> None:
        super().__init__(seed=seed)
        self._register('P', Stoneship())

        self._bind()

        self._register_invariant(
            'P_NeverSolved',
            lambda app: (app._components['P'].state != 'Recovered'),
        )
        self._register_invariant(
            'P_RecoveredMeansSolved',
            lambda app: (not ((app._components['P'].state == 'Recovered') and (not (((((((((app._components['P'].degree and app._components['P'].drainLight) and app._components['P'].airTrap) and app._components['P'].refloat) and app._components['P'].key) and app._components['P'].padlock) and app._components['P'].trap) and app._components['P'].drainRock) and (app._components['P'].tunnels == 2)) and app._components['P'].compass)))),
        )

        self._call_hook('on_init')
        self._evaluate_invariants()

    def _bind(self) -> None:
        pass

    @classmethod
    def main(cls, argv: list[str] | None = None) -> int:
        parser = argparse.ArgumentParser(
            description=f'{cls.__name__}: run spec-driven application',
        )
        parser.add_argument('--run', type=Path)
        parser.add_argument('--seed', type=int, default=0)
        parser.add_argument('--seeds', type=int, default=None)
        args = parser.parse_args(argv)

        if args.run is not None:
            app = cls(seed=args.seed)
            runpy.run_path(str(args.run), init_globals={'app': app})
            return 0

        if args.seeds is not None:
            for seed in range(args.seeds):
                app = cls(seed=seed)
                while app.step() is not None:
                    pass
            return 0

        app = cls(seed=args.seed)
        while app.step() is not None:
            pass
        return 0

if __name__ == '__main__':
    sys.exit(StoneshipGame.main())
