"""
SeleniticSound: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class SeleniticSound(Component):
    initial_state = 'Surface'
    state_constants = ('Surface', 'Console', 'Open',)
    _in_ports = ()
    _out_ports = ()
    _observe_ports = ()
    _option_defaults = {}
    _option_constants = {}
    _typed_var_defaults = {'water': False, 'fissure': False, 'clock': False, 'crystal': False, 'tunnel': False, 'tunnelLight': False, 'aWater': False, 'aFissure': False, 'aClock': False, 'aCrystal': False, 'aTunnel': False, 'step': 0}
    _typed_var_bounds = {'step': (0, 5)}

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='SeleniticSound_LightTheDrippingWaterSymbol',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (not self.water),
            assigns=(('water', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_LightTheFissureSymbol',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (not self.fissure),
            assigns=(('fissure', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_LightTheClockSymbol',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (not self.clock),
            assigns=(('clock', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_LightTheCrystalSymbol',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (not self.crystal),
            assigns=(('crystal', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_LightTheTunnelSymbol',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (not self.tunnel),
            assigns=(('tunnel', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_FlipTheTunnelLightSwitch',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (self.tunnel and (not self.tunnelLight)),
            assigns=(('tunnelLight', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_RotateTheDisplayToAimTheWaterReceiverAtItsSound',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (self.water and (not self.aWater)),
            assigns=(('aWater', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_RotateTheDisplayToAimTheFissureReceiverAtItsSound',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (self.fissure and (not self.aFissure)),
            assigns=(('aFissure', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_RotateTheDisplayToAimTheClockReceiverAtItsSound',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (self.clock and (not self.aClock)),
            assigns=(('aClock', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_RotateTheDisplayToAimTheCrystalReceiverAtItsSound',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (self.crystal and (not self.aCrystal)),
            assigns=(('aCrystal', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_RotateTheDisplayToAimTheTunnelReceiverAtItsSound',
            from_state='Surface',
            to_state='Surface',
            kind='local',
            guard_fn=lambda self: (self.tunnel and (not self.aTunnel)),
            assigns=(('aTunnel', lambda self: True),),
        ),
        Transition(
            name='SeleniticSound_PressSigmaTheDevicePlaysTheOrderCrystalWaterTunnelFissureClock',
            from_state='Surface',
            to_state='Console',
            kind='local',
            guard_fn=lambda self: (((((self.tunnelLight and self.aWater) and self.aFissure) and self.aClock) and self.aCrystal) and self.aTunnel),
        ),
        Transition(
            name='SeleniticSound_SetSlider1ToCRYSTAL',
            from_state='Console',
            to_state='Console',
            kind='local',
            guard_fn=lambda self: (self.step == 0),
            assigns=(('step', lambda self: 1),),
        ),
        Transition(
            name='SeleniticSound_SetSlider2ToWATER',
            from_state='Console',
            to_state='Console',
            kind='local',
            guard_fn=lambda self: (self.step == 1),
            assigns=(('step', lambda self: 2),),
        ),
        Transition(
            name='SeleniticSound_SetSlider3ToTUNNEL',
            from_state='Console',
            to_state='Console',
            kind='local',
            guard_fn=lambda self: (self.step == 2),
            assigns=(('step', lambda self: 3),),
        ),
        Transition(
            name='SeleniticSound_SetSlider4ToFISSURE',
            from_state='Console',
            to_state='Console',
            kind='local',
            guard_fn=lambda self: (self.step == 3),
            assigns=(('step', lambda self: 4),),
        ),
        Transition(
            name='SeleniticSound_SetSlider5ToCLOCK',
            from_state='Console',
            to_state='Console',
            kind='local',
            guard_fn=lambda self: (self.step == 4),
            assigns=(('step', lambda self: 5),),
        ),
        Transition(
            name='SeleniticSound_PressTheButtonTheVesselDoorOpens',
            from_state='Console',
            to_state='Open',
            kind='local',
            guard_fn=lambda self: (self.step == 5),
        ),
        Transition(
            name='SeleniticSound_Solved',
            from_state='Open',
            to_state='Open',
            kind='local',
        ),
        ]
