"""
SoundGame: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

import argparse
import runpy
import sys
from pathlib import Path

from kinner_runtime import (Application, Buffer, Component, DisabledActionError, InvariantViolation, SendSlot, Transition)

from SeleniticSound import SeleniticSound


class SoundGame(Application):
    DisabledActionError = DisabledActionError
    InvariantViolation = InvariantViolation

    @property
    def p_seleniticSoundState(self) -> str:
        return f"P_{self._components['P'].state}"

    @property
    def p_seleniticSoundWater(self) -> bool:
        return self._components['P'].water

    @property
    def p_seleniticSoundFissure(self) -> bool:
        return self._components['P'].fissure

    @property
    def p_seleniticSoundClock(self) -> bool:
        return self._components['P'].clock

    @property
    def p_seleniticSoundCrystal(self) -> bool:
        return self._components['P'].crystal

    @property
    def p_seleniticSoundTunnel(self) -> bool:
        return self._components['P'].tunnel

    @property
    def p_seleniticSoundTunnelLight(self) -> bool:
        return self._components['P'].tunnelLight

    @property
    def p_seleniticSoundAWater(self) -> bool:
        return self._components['P'].aWater

    @property
    def p_seleniticSoundAFissure(self) -> bool:
        return self._components['P'].aFissure

    @property
    def p_seleniticSoundAClock(self) -> bool:
        return self._components['P'].aClock

    @property
    def p_seleniticSoundACrystal(self) -> bool:
        return self._components['P'].aCrystal

    @property
    def p_seleniticSoundATunnel(self) -> bool:
        return self._components['P'].aTunnel

    @property
    def p_seleniticSoundStep(self) -> int:
        return self._components['P'].step

    _tla_state_vars: tuple[str, ...] = ('p_seleniticSoundState', 'p_seleniticSoundWater', 'p_seleniticSoundFissure', 'p_seleniticSoundClock', 'p_seleniticSoundCrystal', 'p_seleniticSoundTunnel', 'p_seleniticSoundTunnelLight', 'p_seleniticSoundAWater', 'p_seleniticSoundAFissure', 'p_seleniticSoundAClock', 'p_seleniticSoundACrystal', 'p_seleniticSoundATunnel', 'p_seleniticSoundStep',)
    _tla_channel_vars: tuple[str, ...] = ()

    def __init__(self, seed: int = 0) -> None:
        super().__init__(seed=seed)
        self._register('P', SeleniticSound())

        self._bind()

        self._register_invariant(
            'P_NeverSolved',
            lambda app: (app._components['P'].state != 'Open'),
        )

        self._call_hook('on_init')
        self._evaluate_invariants()

    def _bind(self) -> None:
        pass

    @classmethod
    def main(cls, argv: list[str] | None = None) -> int:
        parser = argparse.ArgumentParser(
            description=f'{cls.__name__}: run spec-driven application',
        )
        parser.add_argument('--run', type=Path)
        parser.add_argument('--seed', type=int, default=0)
        parser.add_argument('--seeds', type=int, default=None)
        args = parser.parse_args(argv)

        if args.run is not None:
            app = cls(seed=args.seed)
            runpy.run_path(str(args.run), init_globals={'app': app})
            return 0

        if args.seeds is not None:
            for seed in range(args.seeds):
                app = cls(seed=seed)
                while app.step() is not None:
                    pass
            return 0

        app = cls(seed=args.seed)
        while app.step() is not None:
            pass
        return 0

if __name__ == '__main__':
    sys.exit(SoundGame.main())
