"""
SeleniticVoltage: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class SeleniticVoltage(Component):
    initial_state = 'BrickShed'
    state_constants = ('BrickShed', 'Rocket', 'Open',)
    _in_ports = ()
    _out_ports = ()
    _observe_ports = ()
    _option_defaults = {}
    _option_constants = {}
    _typed_var_defaults = {'total': 0, 'b1': False, 'b2': False, 'b3': False, 'b4': False, 'b5': False, 'keyStep': 0}
    _typed_var_bounds = {'total': (0, 80), 'keyStep': (0, 5)}

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='SeleniticVoltage_PressThe22VButton',
            from_state='BrickShed',
            to_state='BrickShed',
            kind='local',
            guard_fn=lambda self: ((not self.b1) and (self.total <= 58)),
            assigns=(('b1', lambda self: True), ('total', lambda self: (self.total + 22)),),
        ),
        Transition(
            name='SeleniticVoltage_ReleaseThe22VButton',
            from_state='BrickShed',
            to_state='BrickShed',
            kind='local',
            guard_fn=lambda self: self.b1,
            assigns=(('b1', lambda self: False), ('total', lambda self: (self.total - 22)),),
        ),
        Transition(
            name='SeleniticVoltage_PressThe19VButton',
            from_state='BrickShed',
            to_state='BrickShed',
            kind='local',
            guard_fn=lambda self: ((not self.b2) and (self.total <= 58)),
            assigns=(('b2', lambda self: True), ('total', lambda self: (self.total + 19)),),
        ),
        Transition(
            name='SeleniticVoltage_ReleaseThe19VButton',
            from_state='BrickShed',
            to_state='BrickShed',
            kind='local',
            guard_fn=lambda self: self.b2,
            assigns=(('b2', lambda self: False), ('total', lambda self: (self.total - 19)),),
        ),
        Transition(
            name='SeleniticVoltage_PressThe18VButton',
            from_state='BrickShed',
            to_state='BrickShed',
            kind='local',
            guard_fn=lambda self: ((not self.b3) and (self.total <= 58)),
            assigns=(('b3', lambda self: True), ('total', lambda self: (self.total + 18)),),
        ),
        Transition(
            name='SeleniticVoltage_ReleaseThe18VButton',
            from_state='BrickShed',
            to_state='BrickShed',
            kind='local',
            guard_fn=lambda self: self.b3,
            assigns=(('b3', lambda self: False), ('total', lambda self: (self.total - 18)),),
        ),
        Transition(
            name='SeleniticVoltage_PressThe10VButton',
            from_state='BrickShed',
            to_state='BrickShed',
            kind='local',
            guard_fn=lambda self: ((not self.b4) and (self.total <= 58)),
            assigns=(('b4', lambda self: True), ('total', lambda self: (self.total + 10)),),
        ),
        Transition(
            name='SeleniticVoltage_ReleaseThe10VButton',
            from_state='BrickShed',
            to_state='BrickShed',
            kind='local',
            guard_fn=lambda self: self.b4,
            assigns=(('b4', lambda self: False), ('total', lambda self: (self.total - 10)),),
        ),
        Transition(
            name='SeleniticVoltage_PressThe8VButton',
            from_state='BrickShed',
            to_state='BrickShed',
            kind='local',
            guard_fn=lambda self: ((not self.b5) and (self.total <= 58)),
            assigns=(('b5', lambda self: True), ('total', lambda self: (self.total + 8)),),
        ),
        Transition(
            name='SeleniticVoltage_ReleaseThe8VButton',
            from_state='BrickShed',
            to_state='BrickShed',
            kind='local',
            guard_fn=lambda self: self.b5,
            assigns=(('b5', lambda self: False), ('total', lambda self: (self.total - 8)),),
        ),
        Transition(
            name='SeleniticVoltage_TheVoltageReadsExactly59TheRocketPowersUp',
            from_state='BrickShed',
            to_state='Rocket',
            kind='local',
            guard_fn=lambda self: (self.total == 59),
        ),
        Transition(
            name='SeleniticVoltage_PressKeyboardKey1InTheSoundOrder',
            from_state='Rocket',
            to_state='Rocket',
            kind='local',
            guard_fn=lambda self: (self.keyStep == 0),
            assigns=(('keyStep', lambda self: 1),),
        ),
        Transition(
            name='SeleniticVoltage_PressKeyboardKey2InTheSoundOrder',
            from_state='Rocket',
            to_state='Rocket',
            kind='local',
            guard_fn=lambda self: (self.keyStep == 1),
            assigns=(('keyStep', lambda self: 2),),
        ),
        Transition(
            name='SeleniticVoltage_PressKeyboardKey3InTheSoundOrder',
            from_state='Rocket',
            to_state='Rocket',
            kind='local',
            guard_fn=lambda self: (self.keyStep == 2),
            assigns=(('keyStep', lambda self: 3),),
        ),
        Transition(
            name='SeleniticVoltage_PressKeyboardKey4InTheSoundOrder',
            from_state='Rocket',
            to_state='Rocket',
            kind='local',
            guard_fn=lambda self: (self.keyStep == 3),
            assigns=(('keyStep', lambda self: 4),),
        ),
        Transition(
            name='SeleniticVoltage_PressKeyboardKey5InTheSoundOrder',
            from_state='Rocket',
            to_state='Rocket',
            kind='local',
            guard_fn=lambda self: (self.keyStep == 4),
            assigns=(('keyStep', lambda self: 5),),
        ),
        Transition(
            name='SeleniticVoltage_PullTheLeverTheSeleniticBookAppears',
            from_state='Rocket',
            to_state='Open',
            kind='local',
            guard_fn=lambda self: (self.keyStep == 5),
        ),
        Transition(
            name='SeleniticVoltage_Solved',
            from_state='Open',
            to_state='Open',
            kind='local',
        ),
        ]
