"""
VoltageGame: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

import argparse
import runpy
import sys
from pathlib import Path

from kinner_runtime import (Application, Buffer, Component, DisabledActionError, InvariantViolation, SendSlot, Transition)

from SeleniticVoltage import SeleniticVoltage


class VoltageGame(Application):
    DisabledActionError = DisabledActionError
    InvariantViolation = InvariantViolation

    @property
    def p_seleniticVoltageState(self) -> str:
        return f"P_{self._components['P'].state}"

    @property
    def p_seleniticVoltageTotal(self) -> int:
        return self._components['P'].total

    @property
    def p_seleniticVoltageB1(self) -> bool:
        return self._components['P'].b1

    @property
    def p_seleniticVoltageB2(self) -> bool:
        return self._components['P'].b2

    @property
    def p_seleniticVoltageB3(self) -> bool:
        return self._components['P'].b3

    @property
    def p_seleniticVoltageB4(self) -> bool:
        return self._components['P'].b4

    @property
    def p_seleniticVoltageB5(self) -> bool:
        return self._components['P'].b5

    @property
    def p_seleniticVoltageKeyStep(self) -> int:
        return self._components['P'].keyStep

    _tla_state_vars: tuple[str, ...] = ('p_seleniticVoltageState', 'p_seleniticVoltageTotal', 'p_seleniticVoltageB1', 'p_seleniticVoltageB2', 'p_seleniticVoltageB3', 'p_seleniticVoltageB4', 'p_seleniticVoltageB5', 'p_seleniticVoltageKeyStep',)
    _tla_channel_vars: tuple[str, ...] = ()

    def __init__(self, seed: int = 0) -> None:
        super().__init__(seed=seed)
        self._register('P', SeleniticVoltage())

        self._bind()

        self._register_invariant(
            'P_NeverSolved',
            lambda app: (app._components['P'].state != 'Open'),
        )

        self._call_hook('on_init')
        self._evaluate_invariants()

    def _bind(self) -> None:
        pass

    @classmethod
    def main(cls, argv: list[str] | None = None) -> int:
        parser = argparse.ArgumentParser(
            description=f'{cls.__name__}: run spec-driven application',
        )
        parser.add_argument('--run', type=Path)
        parser.add_argument('--seed', type=int, default=0)
        parser.add_argument('--seeds', type=int, default=None)
        args = parser.parse_args(argv)

        if args.run is not None:
            app = cls(seed=args.seed)
            runpy.run_path(str(args.run), init_globals={'app': app})
            return 0

        if args.seeds is not None:
            for seed in range(args.seeds):
                app = cls(seed=seed)
                while app.step() is not None:
                    pass
            return 0

        app = cls(seed=args.seed)
        while app.step() is not None:
            pass
        return 0

if __name__ == '__main__':
    sys.exit(VoltageGame.main())
