"""
Book: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class Book(Component):
    initial_state = 'Trapped'
    state_constants = ('Trapped', 'Complete', 'Freed',)
    _in_ports = ('PAGE_IN',)
    _out_ports = ('FREED',)
    _observe_ports = ()
    _option_defaults = {'pagesNeeded': 4, 'revealAt': 0}
    _option_constants = {'PagesNeeded': 'pagesNeeded', 'RevealAt': 'revealAt'}
    _typed_var_defaults = {'pages': 0}
    _typed_var_bounds = {'pages': (0, 'pagesNeeded')}
    _message_set = frozenset({'AddPage', 'Freed'})

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='Book_ACarriedPageIsSlottedInNotYetComplete',
            from_state='Trapped',
            to_state='Trapped',
            kind='receive',
            recv_port='PAGE_IN',
            recv_tag='AddPage',
            guard_fn=lambda self: ((self.pages < (self._options['pagesNeeded'] - 1)) and ((self._options['revealAt'] == 0) or (self.pages != (self._options['revealAt'] - 1)))),
            assigns=(('pages', lambda self: (self.pages + 1)),),
        ),
        Transition(
            name='Book_ThePageThatCompletesTheBookIsSlottedInTheFireplaceCombinationIsNowRevealedStillTrapped',
            from_state='Trapped',
            to_state='Complete',
            kind='receive',
            recv_port='PAGE_IN',
            recv_tag='AddPage',
            guard_fn=lambda self: ((self._options['revealAt'] > 0) and (self.pages == (self._options['revealAt'] - 1))),
            assigns=(('pages', lambda self: (self.pages + 1)),),
        ),
        Transition(
            name='Book_AFurtherPageIsSlottedInStillShortOfFreeing',
            from_state='Complete',
            to_state='Complete',
            kind='receive',
            recv_port='PAGE_IN',
            recv_tag='AddPage',
            guard_fn=lambda self: (self.pages < (self._options['pagesNeeded'] - 1)),
            assigns=(('pages', lambda self: (self.pages + 1)),),
        ),
        Transition(
            name='Book_TheFinalPageIsSlottedInThePersonGoesFreeTheTrap',
            from_state='Complete',
            to_state='Freed',
            kind='send_receive',
            recv_port='PAGE_IN',
            recv_tag='AddPage',
            sends=(SendSlot(port='FREED', tag='Freed'),),
            guard_fn=lambda self: (self.pages == (self._options['pagesNeeded'] - 1)),
            assigns=(('pages', lambda self: (self.pages + 1)),),
        ),
        Transition(
            name='Book_TheFinalPageIsSlottedInThePersonGoesFree',
            from_state='Trapped',
            to_state='Freed',
            kind='send_receive',
            recv_port='PAGE_IN',
            recv_tag='AddPage',
            sends=(SendSlot(port='FREED', tag='Freed'),),
            guard_fn=lambda self: ((self.pages == (self._options['pagesNeeded'] - 1)) and (self._options['revealAt'] == 0)),
            assigns=(('pages', lambda self: (self.pages + 1)),),
        ),
        Transition(
            name='Book_Freed',
            from_state='Freed',
            to_state='Freed',
            kind='local',
        ),
        ]
