"""
Clue: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class Clue(Component):
    initial_state = 'Unseen'
    state_constants = ('Unseen', 'Seen',)
    _in_ports = ('LOOK',)
    _out_ports = ()
    _observe_ports = ()
    _option_defaults = {}
    _option_constants = {}
    _typed_var_defaults = {}
    _message_set = frozenset({'Look'})

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='Clue_ThePlayerLooksAndLearnsWhatItShows',
            from_state='Unseen',
            to_state='Seen',
            kind='receive',
            recv_port='LOOK',
            recv_tag='Look',
        ),
        Transition(
            name='Clue_LooksAgainAlreadyKnown',
            from_state='Seen',
            to_state='Seen',
            kind='receive',
            recv_port='LOOK',
            recv_tag='Look',
        ),
        ]
