"""
Hands: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class Hands(Component):
    initial_state = 'Empty'
    state_constants = ('Empty', 'Full',)
    _in_ports = ('GRAB', 'DROP',)
    _out_ports = ()
    _observe_ports = ()
    _option_defaults = {}
    _option_constants = {}
    _typed_var_defaults = {}
    _message_set = frozenset({'Drop', 'Grab'})

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='Hands_PickSomethingUpHandsNowFull',
            from_state='Empty',
            to_state='Full',
            kind='receive',
            recv_port='GRAB',
            recv_tag='Grab',
        ),
        Transition(
            name='Hands_PutItDownHandsFreeAgain',
            from_state='Full',
            to_state='Empty',
            kind='receive',
            recv_port='DROP',
            recv_tag='Drop',
        ),
        ]
