"""
Item: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class Item(Component):
    initial_state = 'Unclaimed'
    state_constants = ('Unclaimed', 'Held', 'Gone',)
    _in_ports = ('ITEM_CTL',)
    _out_ports = ()
    _observe_ports = ()
    _option_defaults = {'reacquirable': 0}
    _option_constants = {'Reacquirable': 'reacquirable'}
    _typed_var_defaults = {}
    _message_set = frozenset({'Give', 'Take'})

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='Item_IsTaken',
            from_state='Unclaimed',
            to_state='Held',
            kind='receive',
            recv_port='ITEM_CTL',
            recv_tag='Take',
        ),
        Transition(
            name='Item_IsGivenAway',
            from_state='Held',
            to_state='Gone',
            kind='receive',
            recv_port='ITEM_CTL',
            recv_tag='Give',
        ),
        Transition(
            name='Item_IsReacquired',
            from_state='Gone',
            to_state='Held',
            kind='receive',
            recv_port='ITEM_CTL',
            recv_tag='Take',
            guard_fn=lambda self: (self._options['reacquirable'] == 1),
        ),
        ]
