"""
MarkerSwitch: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class MarkerSwitch(Component):
    initial_state = 'Off'
    state_constants = ('Off', 'On',)
    _in_ports = ('FLIP',)
    _out_ports = ()
    _observe_ports = ()
    _option_defaults = {}
    _option_constants = {}
    _typed_var_defaults = {}
    _message_set = frozenset({'Flip'})

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='Switch_FlipTheMarkerSwitchUp',
            from_state='Off',
            to_state='On',
            kind='receive',
            recv_port='FLIP',
            recv_tag='Flip',
        ),
        ]
