"""
NavMyst: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

import argparse
import runpy
import sys
from pathlib import Path

from kinner_runtime import (Application, Buffer, Component, DisabledActionError, InvariantViolation, SendSlot, Transition)

from PlayerLocation import PlayerLocation
from PuzzleStub import PuzzleStub
from Clue import Clue
from MarkerSwitch import MarkerSwitch
from Hands import Hands
from Item import Item
from Book import Book


class NavMyst(Application):
    DisabledActionError = DisabledActionError
    InvariantViolation = InvariantViolation

    @property
    def pL_egoState(self) -> str:
        return f"PL_{self._components['PL'].state}"

    @property
    def mechanicalPuz_puzzleState(self) -> str:
        return f"MechanicalPuz_{self._components['MechanicalPuz'].state}"

    @property
    def stoneshipPuz_puzzleState(self) -> str:
        return f"StoneshipPuz_{self._components['StoneshipPuz'].state}"

    @property
    def channelwoodPuz_puzzleState(self) -> str:
        return f"ChannelwoodPuz_{self._components['ChannelwoodPuz'].state}"

    @property
    def seleniticPuz_puzzleState(self) -> str:
        return f"SeleniticPuz_{self._components['SeleniticPuz'].state}"

    @property
    def dunnyPuz_puzzleState(self) -> str:
        return f"DunnyPuz_{self._components['DunnyPuz'].state}"

    @property
    def clueMechanical_clueState(self) -> str:
        return f"ClueMechanical_{self._components['ClueMechanical'].state}"

    @property
    def clueStoneship_clueState(self) -> str:
        return f"ClueStoneship_{self._components['ClueStoneship'].state}"

    @property
    def clueChannelwood_clueState(self) -> str:
        return f"ClueChannelwood_{self._components['ClueChannelwood'].state}"

    @property
    def clueSelenitic_clueState(self) -> str:
        return f"ClueSelenitic_{self._components['ClueSelenitic'].state}"

    @property
    def fireplaceCombo_clueState(self) -> str:
        return f"FireplaceCombo_{self._components['FireplaceCombo'].state}"

    @property
    def noteClue_clueState(self) -> str:
        return f"NoteClue_{self._components['NoteClue'].state}"

    @property
    def switchDock_switchState(self) -> str:
        return f"SwitchDock_{self._components['SwitchDock'].state}"

    @property
    def switchCabin_switchState(self) -> str:
        return f"SwitchCabin_{self._components['SwitchCabin'].state}"

    @property
    def switchClock_switchState(self) -> str:
        return f"SwitchClock_{self._components['SwitchClock'].state}"

    @property
    def switchGears_switchState(self) -> str:
        return f"SwitchGears_{self._components['SwitchGears'].state}"

    @property
    def switchSpaceShip_switchState(self) -> str:
        return f"SwitchSpaceShip_{self._components['SwitchSpaceShip'].state}"

    @property
    def switchGenerator_switchState(self) -> str:
        return f"SwitchGenerator_{self._components['SwitchGenerator'].state}"

    @property
    def switchTree_switchState(self) -> str:
        return f"SwitchTree_{self._components['SwitchTree'].state}"

    @property
    def switchPlanetarium_switchState(self) -> str:
        return f"SwitchPlanetarium_{self._components['SwitchPlanetarium'].state}"

    @property
    def towerRevealed_clueState(self) -> str:
        return f"TowerRevealed_{self._components['TowerRevealed'].state}"

    @property
    def hands_handsState(self) -> str:
        return f"Hands_{self._components['Hands'].state}"

    @property
    def pageSirrusMechanical_itemState(self) -> str:
        return f"PageSirrusMechanical_{self._components['PageSirrusMechanical'].state}"

    @property
    def pageSirrusStoneship_itemState(self) -> str:
        return f"PageSirrusStoneship_{self._components['PageSirrusStoneship'].state}"

    @property
    def pageSirrusChannelwood_itemState(self) -> str:
        return f"PageSirrusChannelwood_{self._components['PageSirrusChannelwood'].state}"

    @property
    def pageSirrusSelenitic_itemState(self) -> str:
        return f"PageSirrusSelenitic_{self._components['PageSirrusSelenitic'].state}"

    @property
    def pageWhiteSto_itemState(self) -> str:
        return f"PageWhiteSto_{self._components['PageWhiteSto'].state}"

    @property
    def pageWhiteCha_itemState(self) -> str:
        return f"PageWhiteCha_{self._components['PageWhiteCha'].state}"

    @property
    def pageFreebieRed_itemState(self) -> str:
        return f"PageFreebieRed_{self._components['PageFreebieRed'].state}"

    @property
    def sirrus_bookState(self) -> str:
        return f"Sirrus_{self._components['Sirrus'].state}"

    @property
    def sirrus_bookPages(self) -> int:
        return self._components['Sirrus'].pages

    @property
    def atrus_bookState(self) -> str:
        return f"Atrus_{self._components['Atrus'].state}"

    @property
    def atrus_bookPages(self) -> int:
        return self._components['Atrus'].pages

    @property
    def pLATTEMPT_MechanicalToMechanicalPuzATTEMPT(self) -> str:
        return self._channel_phase(self._components['PL'], 'ATTEMPT_Mechanical')

    @property
    def pLATTEMPT_StoneshipToStoneshipPuzATTEMPT(self) -> str:
        return self._channel_phase(self._components['PL'], 'ATTEMPT_Stoneship')

    @property
    def pLATTEMPT_ChannelwoodToChannelwoodPuzATTEMPT(self) -> str:
        return self._channel_phase(self._components['PL'], 'ATTEMPT_Channelwood')

    @property
    def pLATTEMPT_SeleniticToSeleniticPuzATTEMPT(self) -> str:
        return self._channel_phase(self._components['PL'], 'ATTEMPT_Selenitic')

    @property
    def pLATTEMPT_DunnyToDunnyPuzATTEMPT(self) -> str:
        return self._channel_phase(self._components['PL'], 'ATTEMPT_Dunny')

    @property
    def pLREAD_MechanicalToClueMechanicalLOOK(self) -> str:
        return self._channel_phase(self._components['PL'], 'READ_Mechanical')

    @property
    def pLREAD_StoneshipToClueStoneshipLOOK(self) -> str:
        return self._channel_phase(self._components['PL'], 'READ_Stoneship')

    @property
    def pLREAD_ChannelwoodToClueChannelwoodLOOK(self) -> str:
        return self._channel_phase(self._components['PL'], 'READ_Channelwood')

    @property
    def pLREAD_SeleniticToClueSeleniticLOOK(self) -> str:
        return self._channel_phase(self._components['PL'], 'READ_Selenitic')

    @property
    def pLREAD_DunnyToFireplaceComboLOOK(self) -> str:
        return self._channel_phase(self._components['PL'], 'READ_Dunny')

    @property
    def pLREAD_NOTEToNoteClueLOOK(self) -> str:
        return self._channel_phase(self._components['PL'], 'READ_NOTE')

    @property
    def pLFLIP_DockToSwitchDockFLIP(self) -> str:
        return self._channel_phase(self._components['PL'], 'FLIP_Dock')

    @property
    def pLFLIP_CabinToSwitchCabinFLIP(self) -> str:
        return self._channel_phase(self._components['PL'], 'FLIP_Cabin')

    @property
    def pLFLIP_ClockToSwitchClockFLIP(self) -> str:
        return self._channel_phase(self._components['PL'], 'FLIP_Clock')

    @property
    def pLFLIP_GearsToSwitchGearsFLIP(self) -> str:
        return self._channel_phase(self._components['PL'], 'FLIP_Gears')

    @property
    def pLFLIP_SpaceShipToSwitchSpaceShipFLIP(self) -> str:
        return self._channel_phase(self._components['PL'], 'FLIP_SpaceShip')

    @property
    def pLFLIP_GeneratorToSwitchGeneratorFLIP(self) -> str:
        return self._channel_phase(self._components['PL'], 'FLIP_Generator')

    @property
    def pLFLIP_TreeToSwitchTreeFLIP(self) -> str:
        return self._channel_phase(self._components['PL'], 'FLIP_Tree')

    @property
    def pLFLIP_PlanetariumToSwitchPlanetariumFLIP(self) -> str:
        return self._channel_phase(self._components['PL'], 'FLIP_Planetarium')

    @property
    def pLREAD_IMAGERToTowerRevealedLOOK(self) -> str:
        return self._channel_phase(self._components['PL'], 'READ_IMAGER')

    @property
    def pLGRABToHandsGRAB(self) -> str:
        return self._channel_phase(self._components['PL'], 'GRAB')

    @property
    def pLDROPToHandsDROP(self) -> str:
        return self._channel_phase(self._components['PL'], 'DROP')

    @property
    def pLITEMCTL_SirrusMechanicalToPageSirrusMechanicalITEM_CTL(self) -> str:
        return self._channel_phase(self._components['PL'], 'ITEMCTL_SirrusMechanical')

    @property
    def pLITEMCTL_SirrusStoneshipToPageSirrusStoneshipITEM_CTL(self) -> str:
        return self._channel_phase(self._components['PL'], 'ITEMCTL_SirrusStoneship')

    @property
    def pLITEMCTL_SirrusChannelwoodToPageSirrusChannelwoodITEM_CTL(self) -> str:
        return self._channel_phase(self._components['PL'], 'ITEMCTL_SirrusChannelwood')

    @property
    def pLITEMCTL_SirrusSeleniticToPageSirrusSeleniticITEM_CTL(self) -> str:
        return self._channel_phase(self._components['PL'], 'ITEMCTL_SirrusSelenitic')

    @property
    def pLITEMCTL_WhiteStoToPageWhiteStoITEM_CTL(self) -> str:
        return self._channel_phase(self._components['PL'], 'ITEMCTL_WhiteSto')

    @property
    def pLITEMCTL_WhiteChaToPageWhiteChaITEM_CTL(self) -> str:
        return self._channel_phase(self._components['PL'], 'ITEMCTL_WhiteCha')

    @property
    def pLITEMCTL_FreebieRedToPageFreebieRedITEM_CTL(self) -> str:
        return self._channel_phase(self._components['PL'], 'ITEMCTL_FreebieRed')

    @property
    def pLSIRRUS_ADDToSirrusPAGE_IN(self) -> str:
        return self._channel_phase(self._components['PL'], 'SIRRUS_ADD')

    @property
    def pLATRUS_ADDToAtrusPAGE_IN(self) -> str:
        return self._channel_phase(self._components['PL'], 'ATRUS_ADD')

    _tla_state_vars: tuple[str, ...] = ('pL_egoState', 'mechanicalPuz_puzzleState', 'stoneshipPuz_puzzleState', 'channelwoodPuz_puzzleState', 'seleniticPuz_puzzleState', 'dunnyPuz_puzzleState', 'clueMechanical_clueState', 'clueStoneship_clueState', 'clueChannelwood_clueState', 'clueSelenitic_clueState', 'fireplaceCombo_clueState', 'noteClue_clueState', 'switchDock_switchState', 'switchCabin_switchState', 'switchClock_switchState', 'switchGears_switchState', 'switchSpaceShip_switchState', 'switchGenerator_switchState', 'switchTree_switchState', 'switchPlanetarium_switchState', 'towerRevealed_clueState', 'hands_handsState', 'pageSirrusMechanical_itemState', 'pageSirrusStoneship_itemState', 'pageSirrusChannelwood_itemState', 'pageSirrusSelenitic_itemState', 'pageWhiteSto_itemState', 'pageWhiteCha_itemState', 'pageFreebieRed_itemState', 'sirrus_bookState', 'sirrus_bookPages', 'atrus_bookState', 'atrus_bookPages',)
    _tla_channel_vars: tuple[str, ...] = ('pLATTEMPT_MechanicalToMechanicalPuzATTEMPT', 'pLATTEMPT_StoneshipToStoneshipPuzATTEMPT', 'pLATTEMPT_ChannelwoodToChannelwoodPuzATTEMPT', 'pLATTEMPT_SeleniticToSeleniticPuzATTEMPT', 'pLATTEMPT_DunnyToDunnyPuzATTEMPT', 'pLREAD_MechanicalToClueMechanicalLOOK', 'pLREAD_StoneshipToClueStoneshipLOOK', 'pLREAD_ChannelwoodToClueChannelwoodLOOK', 'pLREAD_SeleniticToClueSeleniticLOOK', 'pLREAD_DunnyToFireplaceComboLOOK', 'pLREAD_NOTEToNoteClueLOOK', 'pLFLIP_DockToSwitchDockFLIP', 'pLFLIP_CabinToSwitchCabinFLIP', 'pLFLIP_ClockToSwitchClockFLIP', 'pLFLIP_GearsToSwitchGearsFLIP', 'pLFLIP_SpaceShipToSwitchSpaceShipFLIP', 'pLFLIP_GeneratorToSwitchGeneratorFLIP', 'pLFLIP_TreeToSwitchTreeFLIP', 'pLFLIP_PlanetariumToSwitchPlanetariumFLIP', 'pLREAD_IMAGERToTowerRevealedLOOK', 'pLGRABToHandsGRAB', 'pLDROPToHandsDROP', 'pLITEMCTL_SirrusMechanicalToPageSirrusMechanicalITEM_CTL', 'pLITEMCTL_SirrusStoneshipToPageSirrusStoneshipITEM_CTL', 'pLITEMCTL_SirrusChannelwoodToPageSirrusChannelwoodITEM_CTL', 'pLITEMCTL_SirrusSeleniticToPageSirrusSeleniticITEM_CTL', 'pLITEMCTL_WhiteStoToPageWhiteStoITEM_CTL', 'pLITEMCTL_WhiteChaToPageWhiteChaITEM_CTL', 'pLITEMCTL_FreebieRedToPageFreebieRedITEM_CTL', 'pLSIRRUS_ADDToSirrusPAGE_IN', 'pLATRUS_ADDToAtrusPAGE_IN',)

    def __init__(self, seed: int = 0) -> None:
        super().__init__(seed=seed)
        self._register('PL', PlayerLocation())
        self._register('MechanicalPuz', PuzzleStub(AutoSolve=0))
        self._register('StoneshipPuz', PuzzleStub(AutoSolve=0))
        self._register('ChannelwoodPuz', PuzzleStub(AutoSolve=0))
        self._register('SeleniticPuz', PuzzleStub(AutoSolve=0))
        self._register('DunnyPuz', PuzzleStub(AutoSolve=0))
        self._register('ClueMechanical', Clue())
        self._register('ClueStoneship', Clue())
        self._register('ClueChannelwood', Clue())
        self._register('ClueSelenitic', Clue())
        self._register('FireplaceCombo', Clue())
        self._register('NoteClue', Clue())
        self._register('SwitchDock', MarkerSwitch())
        self._register('SwitchCabin', MarkerSwitch())
        self._register('SwitchClock', MarkerSwitch())
        self._register('SwitchGears', MarkerSwitch())
        self._register('SwitchSpaceShip', MarkerSwitch())
        self._register('SwitchGenerator', MarkerSwitch())
        self._register('SwitchTree', MarkerSwitch())
        self._register('SwitchPlanetarium', MarkerSwitch())
        self._register('TowerRevealed', Clue())
        self._register('Hands', Hands())
        self._register('PageSirrusMechanical', Item())
        self._register('PageSirrusStoneship', Item())
        self._register('PageSirrusChannelwood', Item())
        self._register('PageSirrusSelenitic', Item())
        self._register('PageWhiteSto', Item())
        self._register('PageWhiteCha', Item())
        self._register('PageFreebieRed', Item())
        self._register('Sirrus', Book(PagesNeeded=6, RevealAt=5))
        self._register('Atrus', Book(PagesNeeded=2))

        self._bind()

        self._register_invariant(
            'Sirrus_FreedMeansFull',
            lambda app: (not ((app._components['Sirrus'].state == 'Freed') and (app._components['Sirrus'].pages != app._components['Sirrus']._options['pagesNeeded']))),
        )
        self._register_invariant(
            'Atrus_FreedMeansFull',
            lambda app: (not ((app._components['Atrus'].state == 'Freed') and (app._components['Atrus'].pages != app._components['Atrus']._options['pagesNeeded']))),
        )
        self._register_invariant(
            'Sirrus_CompleteMeansRevealReached',
            lambda app: (not ((app._components['Sirrus'].state == 'Complete') and (app._components['Sirrus'].pages < app._components['Sirrus']._options['revealAt']))),
        )
        self._register_invariant(
            'Atrus_CompleteMeansRevealReached',
            lambda app: (not ((app._components['Atrus'].state == 'Complete') and (app._components['Atrus'].pages < app._components['Atrus']._options['revealAt']))),
        )
        self._register_invariant(
            'Seg0_CluesNotRead',
            lambda app: (not ((((app._components['ClueMechanical'].state == 'Seen') and (app._components['ClueStoneship'].state == 'Seen')) and (app._components['ClueChannelwood'].state == 'Seen')) and (app._components['ClueSelenitic'].state == 'Seen'))),
        )
        self._register_invariant(
            'Seg1_ComboNotRevealed',
            lambda app: (app._components['FireplaceCombo'].state != 'Seen'),
        )
        self._register_invariant(
            'Seg2_StoHalfNotIn',
            lambda app: (app._components['PageWhiteSto'].state != 'Gone'),
        )
        self._register_invariant(
            'AtrusNeverFreed',
            lambda app: (app._components['Atrus'].state != 'Freed'),
        )

        self._call_hook('on_init')
        self._evaluate_invariants()

    def _bind(self) -> None:
        self._channel(self._components['PL'], 'ATTEMPT_Mechanical', self._components['MechanicalPuz'], 'ATTEMPT')
        self._channel(self._components['PL'], 'ATTEMPT_Stoneship', self._components['StoneshipPuz'], 'ATTEMPT')
        self._channel(self._components['PL'], 'ATTEMPT_Channelwood', self._components['ChannelwoodPuz'], 'ATTEMPT')
        self._channel(self._components['PL'], 'ATTEMPT_Selenitic', self._components['SeleniticPuz'], 'ATTEMPT')
        self._channel(self._components['PL'], 'ATTEMPT_Dunny', self._components['DunnyPuz'], 'ATTEMPT')
        self._channel(self._components['PL'], 'READ_Mechanical', self._components['ClueMechanical'], 'LOOK')
        self._channel(self._components['PL'], 'READ_Stoneship', self._components['ClueStoneship'], 'LOOK')
        self._channel(self._components['PL'], 'READ_Channelwood', self._components['ClueChannelwood'], 'LOOK')
        self._channel(self._components['PL'], 'READ_Selenitic', self._components['ClueSelenitic'], 'LOOK')
        self._channel(self._components['PL'], 'READ_Dunny', self._components['FireplaceCombo'], 'LOOK')
        self._channel(self._components['PL'], 'READ_NOTE', self._components['NoteClue'], 'LOOK')
        self._channel(self._components['PL'], 'FLIP_Dock', self._components['SwitchDock'], 'FLIP')
        self._channel(self._components['PL'], 'FLIP_Cabin', self._components['SwitchCabin'], 'FLIP')
        self._channel(self._components['PL'], 'FLIP_Clock', self._components['SwitchClock'], 'FLIP')
        self._channel(self._components['PL'], 'FLIP_Gears', self._components['SwitchGears'], 'FLIP')
        self._channel(self._components['PL'], 'FLIP_SpaceShip', self._components['SwitchSpaceShip'], 'FLIP')
        self._channel(self._components['PL'], 'FLIP_Generator', self._components['SwitchGenerator'], 'FLIP')
        self._channel(self._components['PL'], 'FLIP_Tree', self._components['SwitchTree'], 'FLIP')
        self._channel(self._components['PL'], 'FLIP_Planetarium', self._components['SwitchPlanetarium'], 'FLIP')
        self._channel(self._components['PL'], 'READ_IMAGER', self._components['TowerRevealed'], 'LOOK')
        self._channel(self._components['PL'], 'GRAB', self._components['Hands'], 'GRAB')
        self._channel(self._components['PL'], 'DROP', self._components['Hands'], 'DROP')
        self._channel(self._components['PL'], 'ITEMCTL_SirrusMechanical', self._components['PageSirrusMechanical'], 'ITEM_CTL')
        self._channel(self._components['PL'], 'ITEMCTL_SirrusStoneship', self._components['PageSirrusStoneship'], 'ITEM_CTL')
        self._channel(self._components['PL'], 'ITEMCTL_SirrusChannelwood', self._components['PageSirrusChannelwood'], 'ITEM_CTL')
        self._channel(self._components['PL'], 'ITEMCTL_SirrusSelenitic', self._components['PageSirrusSelenitic'], 'ITEM_CTL')
        self._channel(self._components['PL'], 'ITEMCTL_WhiteSto', self._components['PageWhiteSto'], 'ITEM_CTL')
        self._channel(self._components['PL'], 'ITEMCTL_WhiteCha', self._components['PageWhiteCha'], 'ITEM_CTL')
        self._channel(self._components['PL'], 'ITEMCTL_FreebieRed', self._components['PageFreebieRed'], 'ITEM_CTL')
        self._channel(self._components['PL'], 'SIRRUS_ADD', self._components['Sirrus'], 'PAGE_IN')
        self._channel(self._components['PL'], 'ATRUS_ADD', self._components['Atrus'], 'PAGE_IN')
        self._observe(self._components['PL'], 'PUZZLE_Mechanical', self._components['MechanicalPuz'])
        self._observe(self._components['PL'], 'PUZZLE_Stoneship', self._components['StoneshipPuz'])
        self._observe(self._components['PL'], 'PUZZLE_Channelwood', self._components['ChannelwoodPuz'])
        self._observe(self._components['PL'], 'PUZZLE_Selenitic', self._components['SeleniticPuz'])
        self._observe(self._components['PL'], 'PUZZLE_Dunny', self._components['DunnyPuz'])
        self._observe(self._components['PL'], 'CLUE_Mechanical', self._components['ClueMechanical'])
        self._observe(self._components['PL'], 'CLUE_Stoneship', self._components['ClueStoneship'])
        self._observe(self._components['PL'], 'CLUE_Channelwood', self._components['ClueChannelwood'])
        self._observe(self._components['PL'], 'CLUE_Selenitic', self._components['ClueSelenitic'])
        self._observe(self._components['PL'], 'CLUE_Dunny', self._components['FireplaceCombo'])
        self._observe(self._components['PL'], 'BOOK_Sirrus', self._components['Sirrus'])
        self._observe(self._components['PL'], 'NOTE', self._components['NoteClue'])
        self._observe(self._components['PL'], 'SWITCH_Dock', self._components['SwitchDock'])
        self._observe(self._components['PL'], 'SWITCH_Cabin', self._components['SwitchCabin'])
        self._observe(self._components['PL'], 'SWITCH_Clock', self._components['SwitchClock'])
        self._observe(self._components['PL'], 'SWITCH_Gears', self._components['SwitchGears'])
        self._observe(self._components['PL'], 'SWITCH_SpaceShip', self._components['SwitchSpaceShip'])
        self._observe(self._components['PL'], 'SWITCH_Generator', self._components['SwitchGenerator'])
        self._observe(self._components['PL'], 'SWITCH_Tree', self._components['SwitchTree'])
        self._observe(self._components['PL'], 'SWITCH_Planetarium', self._components['SwitchPlanetarium'])
        self._observe(self._components['PL'], 'TOWER', self._components['TowerRevealed'])
        self._observe(self._components['PL'], 'HANDS', self._components['Hands'])
        self._observe(self._components['PL'], 'PAGE_SirrusMechanical', self._components['PageSirrusMechanical'])
        self._observe(self._components['PL'], 'PAGE_SirrusStoneship', self._components['PageSirrusStoneship'])
        self._observe(self._components['PL'], 'PAGE_SirrusChannelwood', self._components['PageSirrusChannelwood'])
        self._observe(self._components['PL'], 'PAGE_SirrusSelenitic', self._components['PageSirrusSelenitic'])
        self._observe(self._components['PL'], 'PAGE_WhiteSto', self._components['PageWhiteSto'])
        self._observe(self._components['PL'], 'PAGE_WhiteCha', self._components['PageWhiteCha'])
        self._observe(self._components['PL'], 'PAGE_FreebieRed', self._components['PageFreebieRed'])
        self._observe(self._components['MechanicalPuz'], 'CLUE', self._components['ClueMechanical'])
        self._observe(self._components['StoneshipPuz'], 'CLUE', self._components['ClueStoneship'])
        self._observe(self._components['ChannelwoodPuz'], 'CLUE', self._components['ClueChannelwood'])
        self._observe(self._components['SeleniticPuz'], 'CLUE', self._components['ClueSelenitic'])
        self._observe(self._components['DunnyPuz'], 'CLUE', self._components['FireplaceCombo'])

    @classmethod
    def main(cls, argv: list[str] | None = None) -> int:
        parser = argparse.ArgumentParser(
            description=f'{cls.__name__}: run spec-driven application',
        )
        parser.add_argument('--run', type=Path)
        parser.add_argument('--seed', type=int, default=0)
        parser.add_argument('--seeds', type=int, default=None)
        args = parser.parse_args(argv)

        if args.run is not None:
            app = cls(seed=args.seed)
            runpy.run_path(str(args.run), init_globals={'app': app})
            return 0

        if args.seeds is not None:
            for seed in range(args.seeds):
                app = cls(seed=seed)
                while app.step() is not None:
                    pass
            return 0

        app = cls(seed=args.seed)
        while app.step() is not None:
            pass
        return 0

if __name__ == '__main__':
    sys.exit(NavMyst.main())
