"""
PuzzleStub: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class PuzzleStub(Component):
    initial_state = 'Hidden'
    state_constants = ('Hidden', 'Located', 'Solved',)
    _in_ports = ('ATTEMPT', 'RESOLVE',)
    _out_ports = ('HOST',)
    _observe_ports = ('CLUE',)
    _option_defaults = {'autoSolve': 1}
    _option_constants = {'AutoSolve': 'autoSolve'}
    _typed_var_defaults = {}
    _message_set = frozenset({'Attempt', 'Request', 'Solved'})

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='Puzzle_ThePlayerAttemptsThePuzzleAutoSolveStubMode',
            from_state='Hidden',
            to_state='Located',
            kind='receive',
            recv_port='ATTEMPT',
            recv_tag='Attempt',
            guard_fn=lambda self: (self._options['autoSolve'] == 1),
        ),
        Transition(
            name='Puzzle_ThePlayerAttemptsThePuzzleFireAtTheHostGoSolveThis',
            from_state='Hidden',
            to_state='Located',
            kind='send_receive',
            recv_port='ATTEMPT',
            recv_tag='Attempt',
            sends=(SendSlot(port='HOST', tag='Request'),),
            guard_fn=lambda self: (self._options['autoSolve'] == 0),
        ),
        Transition(
            name='Puzzle_TheMiniPuzzleAutoWinsThePlayerHasSeenTheClue',
            from_state='Located',
            to_state='Solved',
            kind='local',
            guard_fn=lambda self: ((self._options['autoSolve'] == 1) and (self._observed['CLUE'].state == 'Seen')),
        ),
        Transition(
            name='Puzzle_TheHostReportsThePuzzleSolved',
            from_state='Located',
            to_state='Solved',
            kind='receive',
            recv_port='RESOLVE',
            recv_tag='Solved',
            guard_fn=lambda self: (self._options['autoSolve'] == 0),
        ),
        Transition(
            name='Puzzle_StaysSolved',
            from_state='Solved',
            to_state='Solved',
            kind='local',
        ),
        ]
