"""
FortressGame: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

import argparse
import runpy
import sys
from pathlib import Path

from kinner_runtime import (Application, Buffer, Component, DisabledActionError, InvariantViolation, SendSlot, Transition)

from MechanicalFortress import MechanicalFortress


class FortressGame(Application):
    DisabledActionError = DisabledActionError
    InvariantViolation = InvariantViolation

    @property
    def p_mechanicalFortressState(self) -> str:
        return f"P_{self._components['P'].state}"

    @property
    def p_mechanicalFortressImgr(self) -> bool:
        return self._components['P'].imgr

    @property
    def p_mechanicalFortressPageDoor(self) -> bool:
        return self._components['P'].pageDoor

    @property
    def p_mechanicalFortressPos(self) -> int:
        return self._components['P'].pos

    @property
    def p_mechanicalFortressS0(self) -> bool:
        return self._components['P'].s0

    @property
    def p_mechanicalFortressS1(self) -> bool:
        return self._components['P'].s1

    @property
    def p_mechanicalFortressS2(self) -> bool:
        return self._components['P'].s2

    @property
    def p_mechanicalFortressS3(self) -> bool:
        return self._components['P'].s3

    _tla_state_vars: tuple[str, ...] = ('p_mechanicalFortressState', 'p_mechanicalFortressImgr', 'p_mechanicalFortressPageDoor', 'p_mechanicalFortressPos', 'p_mechanicalFortressS0', 'p_mechanicalFortressS1', 'p_mechanicalFortressS2', 'p_mechanicalFortressS3',)
    _tla_channel_vars: tuple[str, ...] = ()

    def __init__(self, seed: int = 0) -> None:
        super().__init__(seed=seed)
        self._register('P', MechanicalFortress())

        self._bind()

        self._register_invariant(
            'P_NeverSolved',
            lambda app: (app._components['P'].state != 'Done'),
        )
        self._register_invariant(
            'P_DoneMeansSolved',
            lambda app: (not ((app._components['P'].state == 'Done') and (not ((((app._components['P'].imgr and app._components['P'].s0) and app._components['P'].s1) and app._components['P'].s2) and app._components['P'].s3)))),
        )

        self._call_hook('on_init')
        self._evaluate_invariants()

    def _bind(self) -> None:
        pass

    @classmethod
    def main(cls, argv: list[str] | None = None) -> int:
        parser = argparse.ArgumentParser(
            description=f'{cls.__name__}: run spec-driven application',
        )
        parser.add_argument('--run', type=Path)
        parser.add_argument('--seed', type=int, default=0)
        parser.add_argument('--seeds', type=int, default=None)
        args = parser.parse_args(argv)

        if args.run is not None:
            app = cls(seed=args.seed)
            runpy.run_path(str(args.run), init_globals={'app': app})
            return 0

        if args.seeds is not None:
            for seed in range(args.seeds):
                app = cls(seed=seed)
                while app.step() is not None:
                    pass
            return 0

        app = cls(seed=args.seed)
        while app.step() is not None:
            pass
        return 0

if __name__ == '__main__':
    sys.exit(FortressGame.main())
