"""
MechanicalFortress: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class MechanicalFortress(Component):
    initial_state = 'Bottom'
    state_constants = ('Bottom', 'Throne', 'Hallway', 'InElevator', 'PressedButton', 'OnFortress', 'AtControls', 'Oriented', 'Podium', 'Done',)
    _in_ports = ()
    _out_ports = ()
    _observe_ports = ()
    _option_defaults = {}
    _option_constants = {}
    _typed_var_defaults = {'imgr': False, 'pageDoor': False, 'pos': 0, 's0': False, 's1': False, 's2': False, 's3': False}
    _typed_var_bounds = {'pos': (0, 3)}

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='MechanicalFortress_EnterTheFortressAndExploreTheThroneRooms',
            from_state='Bottom',
            to_state='Throne',
            kind='local',
        ),
        Transition(
            name='MechanicalFortress_OpenTheDoorBehindAThroneABrotherPage',
            from_state='Throne',
            to_state='Throne',
            kind='local',
            guard_fn=lambda self: (not self.pageDoor),
            assigns=(('pageDoor', lambda self: True),),
        ),
        Transition(
            name='MechanicalFortress_StudyTheImagerNoteWhichNoiseMapsToEachDirection',
            from_state='Throne',
            to_state='Throne',
            kind='local',
            guard_fn=lambda self: (not self.imgr),
            assigns=(('imgr', lambda self: True),),
        ),
        Transition(
            name='MechanicalFortress_LowerTheHallwayStairsRedButtonAndWorkTheLeverReleaseOnTheRedSymbol',
            from_state='Throne',
            to_state='Hallway',
            kind='local',
        ),
        Transition(
            name='MechanicalFortress_RideTheElevatorUp',
            from_state='Hallway',
            to_state='InElevator',
            kind='local',
        ),
        Transition(
            name='MechanicalFortress_StepOutNormallyCarStaysUp',
            from_state='InElevator',
            to_state='OnFortress',
            kind='local',
        ),
        Transition(
            name='MechanicalFortress_ControlsOutOfReachStepBackIn',
            from_state='OnFortress',
            to_state='InElevator',
            kind='local',
        ),
        Transition(
            name='MechanicalFortress_PressTheDownButton',
            from_state='InElevator',
            to_state='PressedButton',
            kind='local',
        ),
        Transition(
            name='MechanicalFortress_SlipOutBeforeTheCarDropsRoofControlsExposed',
            from_state='PressedButton',
            to_state='AtControls',
            kind='local',
        ),
        Transition(
            name='MechanicalFortress_TooSlowRideBackDown',
            from_state='PressedButton',
            to_state='Bottom',
            kind='local',
        ),
        Transition(
            name='MechanicalFortress_RotateToTheNextPosition',
            from_state='AtControls',
            to_state='AtControls',
            kind='local',
            guard_fn=lambda self: (self.pos < 3),
            assigns=(('pos', lambda self: (self.pos + 1)),),
        ),
        Transition(
            name='MechanicalFortress_RotatePastTheLastPosition',
            from_state='AtControls',
            to_state='AtControls',
            kind='local',
            guard_fn=lambda self: (self.pos == 3),
            assigns=(('pos', lambda self: 0),),
        ),
        Transition(
            name='MechanicalFortress_NoteTheExteriorSymbolPosition0',
            from_state='AtControls',
            to_state='AtControls',
            kind='local',
            guard_fn=lambda self: ((self.pos == 0) and (not self.s0)),
            assigns=(('s0', lambda self: True),),
        ),
        Transition(
            name='MechanicalFortress_NoteTheExteriorSymbolPosition1',
            from_state='AtControls',
            to_state='AtControls',
            kind='local',
            guard_fn=lambda self: ((self.pos == 1) and (not self.s1)),
            assigns=(('s1', lambda self: True),),
        ),
        Transition(
            name='MechanicalFortress_NoteTheExteriorSymbolPosition2',
            from_state='AtControls',
            to_state='AtControls',
            kind='local',
            guard_fn=lambda self: ((self.pos == 2) and (not self.s2)),
            assigns=(('s2', lambda self: True),),
        ),
        Transition(
            name='MechanicalFortress_NoteTheExteriorSymbolPosition3',
            from_state='AtControls',
            to_state='AtControls',
            kind='local',
            guard_fn=lambda self: ((self.pos == 3) and (not self.s3)),
            assigns=(('s3', lambda self: True),),
        ),
        Transition(
            name='MechanicalFortress_LockTheFortressFacingSouthTheHeadingTheSymbolsPointTo',
            from_state='AtControls',
            to_state='Oriented',
            kind='local',
            guard_fn=lambda self: ((((self.imgr and self.s0) and self.s1) and self.s2) and self.s3),
        ),
        Transition(
            name='MechanicalFortress_CrossTheBridgeAndSetTheFinalPodiumToMatchTheSymbolsSeenAtTheOtherRotationPositions',
            from_state='Oriented',
            to_state='Podium',
            kind='local',
        ),
        Transition(
            name='MechanicalFortress_PressTheRedButtonTheStairsToTheMystLinkingBookDescend',
            from_state='Podium',
            to_state='Done',
            kind='local',
        ),
        Transition(
            name='MechanicalFortress_Done',
            from_state='Done',
            to_state='Done',
            kind='local',
        ),
        ]
