"""
Planetarium: generated by earhart compile --target python (kinner_module).

Do not edit by hand. Source of truth is the .kinner.json.
"""
from __future__ import annotations

from kinner_runtime import Component, SendSlot, Transition


class Planetarium(Component):
    initial_state = 'InPlanetarium'
    state_constants = ('InPlanetarium', 'AtBirdbath', 'Open',)
    _in_ports = ()
    _out_ports = ()
    _observe_ports = ()
    _option_defaults = {}
    _option_constants = {}
    _typed_var_defaults = {'c1': False, 'c2': False, 'c3': False}

    def _build_transitions(self) -> list[Transition]:
        return [
        Transition(
            name='Planetarium_SetTheFirstDateRecordItsConstellation',
            from_state='InPlanetarium',
            to_state='InPlanetarium',
            kind='local',
            guard_fn=lambda self: (not self.c1),
            assigns=(('c1', lambda self: True),),
        ),
        Transition(
            name='Planetarium_SetTheSecondDateRecordItsConstellation',
            from_state='InPlanetarium',
            to_state='InPlanetarium',
            kind='local',
            guard_fn=lambda self: (not self.c2),
            assigns=(('c2', lambda self: True),),
        ),
        Transition(
            name='Planetarium_SetTheThirdDateRecordItsConstellation',
            from_state='InPlanetarium',
            to_state='InPlanetarium',
            kind='local',
            guard_fn=lambda self: (not self.c3),
            assigns=(('c3', lambda self: True),),
        ),
        Transition(
            name='Planetarium_AllThreeConstellationsMatchedGoToTheBirdbath',
            from_state='InPlanetarium',
            to_state='AtBirdbath',
            kind='local',
            guard_fn=lambda self: ((self.c1 and self.c2) and self.c3),
        ),
        Transition(
            name='Planetarium_PressTheThreeButtonsNamingTheConstellationsTheShipsRise',
            from_state='AtBirdbath',
            to_state='Open',
            kind='local',
        ),
        Transition(
            name='Planetarium_Solved',
            from_state='Open',
            to_state='Open',
            kind='local',
        ),
        ]
